from __future__ import annotations


FIXTURE_VERSION = "p3.0-v1"
ALGORITHM_VERSION = "p3.0-v1"
THRESHOLD_VERSION = "p3.0-conservative-v1"
SEVERITY_VERSION = "p3.0-v1"
P3_1_ALGORITHM_VERSION = "p3.1-base-rolling-v1"
P3_1_SEVERITY_VERSION = "p3.1-v1"
TEMPLATE_ID = "TG_ONCHAIN_FLOW_ALERT"
TRANSFER_TOPIC = (
    "0xddf252ad1be2c89b69c2b068fc378daa"
    "952ba7f163c4a11628f55a4df523b3ef"
)
ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"
BASE_CHAIN_ID = 8453
BASE_CHAIN_NAME = "Base"

WINDOW_15M_SEC = 15 * 60
WINDOW_60M_SEC = 60 * 60

TOKEN_ACTIVITY_SCHEMA_VERSION = 1
TOKEN_ACTIVITY_MAX_WINDOW_HOURS_HARD = 24
TOKEN_ACTIVITY_MAX_EVENTS_HARD = 5000
TOKEN_ACTIVITY_MAX_RPC_REQUESTS_HARD = 256
TOKEN_ACTIVITY_MAX_UNIQUE_BLOCK_HEADERS_HARD = 2000
TOKEN_ACTIVITY_TOP_N_HARD = 100
TOKEN_ACTIVITY_BLOCK_SEARCH_MAX_CALLS_HARD = 32

OAR_ANALYSIS_SCHEMA_VERSION = 1
OAR_BEHAVIOR_ALGORITHM_VERSION = "oar-behavior-v1"
OAR_WALLET_GROUP_ALGORITHM_VERSION = "oar-wallet-group-v1"
OAR_AI_CONTEXT_SCHEMA_VERSION = 2
OAR_AI_OUTPUT_SCHEMA_VERSION = 1
OAR_AI_PROMPT_VERSION = "oar-ai-prompt-v2"
OAR_REPORT_SCHEMA_VERSION = 1
OAR_REPORT_ALGORITHM_VERSION = "oar-report-v1"
OAR_AUTOMATION_SCHEMA_VERSION = 2
OAR_BEHAVIOR_MIN_TX_HARD = 100
OAR_BEHAVIOR_MIN_ACTIVE_BUCKETS_HARD = 96
OAR_PATTERN_MIN_WALLETS_HARD = 100
OAR_PATTERN_MIN_TX_HARD = 100
OAR_WALLET_SYNC_WINDOW_SEC_HARD = 1800
OAR_MAX_ANALYZED_WALLETS_HARD = 200
OAR_MAX_WALLET_GROUPS_HARD = 50
OAR_MAX_SOURCE_EVENT_IDS_HARD = 200
OAR_BRIDGE_MAX_SIGNALS_PER_CYCLE_HARD = 500
OAR_WATCH_MAX_ACTIVE_TOKENS_HARD = 200
OAR_WATCH_MAX_TOKENS_PER_CYCLE_HARD = 20
OAR_WATCH_MAX_RPC_REQUESTS_PER_CYCLE_HARD = 5000

DIRECTIONAL_FLOW_TYPES = frozenset({"inflow", "outflow"})
NON_DIRECTIONAL_FLOW_TYPES = frozenset(
    {"internal", "cross_cex", "consolidation", "mint", "burn", "non_cex"}
)
FLOW_TYPES = DIRECTIONAL_FLOW_TYPES | NON_DIRECTIONAL_FLOW_TYPES

PRODUCTION_WRITE_PATHS = (
    "data/signals.db",
    "data/market_snapshots.db",
    "data/realtime_features.db",
    "data/tg_push_history.json",
    "data/tg_outbox.json",
    "data/tg_topic_routes.json",
)
