from __future__ import annotations

import argparse
import base64
import hashlib
import textwrap
import zlib
from pathlib import Path


GLYPH_WIDTH = 12
GLYPH_HEIGHT = 15
FONT_SIZE = 12
FONT_WEIGHT = 500

# This is the immutable glyph order introduced with chart_font_zh.py in
# bc6b2621edc512f6a1c41c54fbe78f1bb8fe1b07. New glyphs are appended so
# existing indexes and raster bytes remain stable.
BASE_GLYPH_ORDER = (
    "0123456789/\xb7未知永续合约黄金白银铂钯原油天然气铜指数基杠杆股票代币大宗商品外汇加密核心主流山寨小时结构分钟触发第轮事件形态突破确认扫高低假失效整理区间关键位安已收线"
)

# Formal chart copy requested by the product plus existing runtime fallback
# copy. Sorting only the missing characters keeps subsequent generations stable.
REQUIRED_CHART_TEXT = (
    "开收量结构转空多顺势高估中间价低估已收线"
    "币安永续合约小时真实数据仅使用K线未分类"
    "开 0.05062 +1.23% 20:00"
    ".:%+-"
)

# Windows-distributed NotoSansSC-VF.ttf, version
# "2.04;241114210130;non-release". Its embedded license record is OFL-1.1.
EXPECTED_FONT_SHA256 = (
    "763146584cf0710223441356b4395e279021b0806c196614377a7a0174ae074a"
)
# Pixel/advance fingerprint of BASE_GLYPH_ORDER. This rejects a different
# Pillow/FreeType rasterizer before it can silently redraw existing glyphs.
EXPECTED_BASE_RASTER_SHA256 = (
    "52a06ba7ea26055d08a09d1c610f58595d3e145a5e4cf239731c8f1dc6481a0f"
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FONT_PATH = Path(r"C:\Windows\Fonts\NotoSansSC-VF.ttf")
DEFAULT_OUTPUT_PATH = (
    REPOSITORY_ROOT / "radars" / "launch_warning" / "chart_font_zh.py"
)


def _glyph_order() -> str:
    additional = sorted(
        set(REQUIRED_CHART_TEXT).difference(BASE_GLYPH_ORDER).difference(" "),
        key=ord,
    )
    return BASE_GLYPH_ORDER + "".join(additional)


def _load_font(font_path: Path):
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError as exc:  # pragma: no cover - developer-only dependency
        raise SystemExit(
            "Pillow is required only to regenerate chart_font_zh.py"
        ) from exc

    font_bytes = font_path.read_bytes()
    digest = hashlib.sha256(font_bytes).hexdigest()
    if digest != EXPECTED_FONT_SHA256:
        raise SystemExit(
            f"unexpected Noto Sans SC source hash: {digest}; "
            f"expected {EXPECTED_FONT_SHA256}"
        )

    font = ImageFont.truetype(str(font_path), FONT_SIZE)
    font.set_variation_by_axes([FONT_WEIGHT])
    return Image, ImageDraw, font


def _render_glyphs(font_path: Path, glyph_order: str) -> tuple[bytes, bytes]:
    Image, ImageDraw, font = _load_font(font_path)
    alpha = bytearray()
    advances = bytearray()

    for character in glyph_order:
        image = Image.new("L", (GLYPH_WIDTH, GLYPH_HEIGHT), 0)
        ImageDraw.Draw(image).text((0, 0), character, font=font, fill=255)
        pixels = bytes(image.getdata())
        if not any(pixels):
            raise SystemExit(f"source font produced an empty glyph for {character!r}")
        alpha.extend(pixels)

        advance = round(font.getlength(character))
        if not 1 <= advance <= 255:
            raise SystemExit(
                f"unsupported horizontal advance {advance} for {character!r}"
            )
        advances.append(advance)

    return bytes(alpha), bytes(advances)


def _python_string(value: str) -> str:
    escaped = value.encode("unicode_escape").decode("ascii")
    return f'"{escaped}"'


def _encoded_lines(alpha: bytes) -> str:
    encoded = base64.b85encode(zlib.compress(alpha, level=9)).decode("ascii")
    return "\n".join(
        f'        "{chunk}"'
        for chunk in textwrap.wrap(encoded, width=100)
    )


def _module_source(
    glyph_order: str,
    base_alpha: bytes,
    additional_alpha: bytes,
    advances: bytes,
) -> str:
    base_encoded_lines = _encoded_lines(base_alpha)
    additional_encoded_lines = _encoded_lines(additional_alpha)
    return f'''from __future__ import annotations

import base64
import zlib
from typing import Final


# Compact chart-only raster subset generated from Noto Sans SC at weight 500.
# Generated by scripts/generate_chart_font_zh.py from the pinned source font.
# Noto Sans CJK is licensed under SIL Open Font License 1.1; see
# licenses/NotoSansSC-OFL.txt. The full font is not shipped or needed at runtime.
GLYPH_WIDTH: Final = {GLYPH_WIDTH}
GLYPH_HEIGHT: Final = {GLYPH_HEIGHT}
GLYPH_ORDER: Final = (
    {_python_string(glyph_order)}
)
GLYPH_ADVANCES: Final = bytes.fromhex(
    "{advances.hex()}"
)
_BASE_GLYPH_ALPHA: Final = zlib.decompress(
    base64.b85decode(
{base_encoded_lines}
    )
)
_ADDITIONAL_GLYPH_ALPHA: Final = zlib.decompress(
    base64.b85decode(
{additional_encoded_lines}
    )
)
_GLYPH_ALPHA: Final = _BASE_GLYPH_ALPHA + _ADDITIONAL_GLYPH_ALPHA
_GLYPH_SIZE: Final = GLYPH_WIDTH * GLYPH_HEIGHT


def glyph_alpha(character: str) -> tuple[memoryview, int] | None:
    """Return one immutable grayscale glyph and its horizontal advance."""

    candidate = str(character or "")[:1]
    if not candidate:
        return None
    index = GLYPH_ORDER.find(candidate)
    if index < 0:
        return None
    start = index * _GLYPH_SIZE
    return (
        memoryview(_GLYPH_ALPHA)[start:start + _GLYPH_SIZE],
        int(GLYPH_ADVANCES[index]),
    )


def missing_glyphs(value: str) -> set[str]:
    """Return non-space characters unavailable to the compact chart font."""

    return {{
        character
        for character in str(value or "")
        if character != " " and character not in GLYPH_ORDER
    }}


__all__ = [
    "GLYPH_HEIGHT",
    "GLYPH_WIDTH",
    "glyph_alpha",
    "missing_glyphs",
]
'''


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the compact OFL-licensed Chinese chart font."
    )
    parser.add_argument("--font", type=Path, default=DEFAULT_FONT_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the generated module differs instead of writing it",
    )
    args = parser.parse_args()

    base_alpha, base_advances = _render_glyphs(args.font, BASE_GLYPH_ORDER)
    base_digest = hashlib.sha256(base_alpha + base_advances).hexdigest()
    if base_digest != EXPECTED_BASE_RASTER_SHA256:
        raise SystemExit(
            "the local Pillow/FreeType rasterizer does not reproduce the "
            f"existing subset: {base_digest}"
        )

    glyph_order = _glyph_order()
    alpha, advances = _render_glyphs(args.font, glyph_order)
    source = _module_source(
        glyph_order,
        base_alpha,
        alpha[len(base_alpha):],
        advances,
    )

    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != source:
            raise SystemExit(f"generated font module is stale: {args.output}")
        print(f"font module is reproducible: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(source)
    print(f"wrote {len(glyph_order)} glyphs to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
